# Generated by Django 5.2.8 on 2026-04-20 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamperapp', '0003_alter_hamper_id_alter_order_id_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='token',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='otp_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
