# Generated by Django 6.0.4 on 2026-05-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamperapp', '0007_order_country_order_email_order_phone_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verifying', 'Verifying Payment'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
