# Generated by Django 5.2.8 on 2026-05-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamperapp', '0008_order_payment_screenshot_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
